const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS',
FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE_REQUEST',
FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE',
FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS',
FETCH_PLANETS_REQUEST = 'FETCH_PLANETS_REQUEST',
FETCH_PLANETS_FAILURE = 'FETCH_PLANETS_FAILURE',
FETCH_STARSHIPS_SUCCESS = 'FETCH_STARSHIPS_SUCCESS',
FETCH_STARSHIPS_REQUEST = 'FETCH_STARSHIPS_REQUEST',
FETCH_STARSHIPS_FAILURE = 'FETCH_STARSHIPS_FAILURE';

export {
    FETCH_PEOPLE_SUCCESS,
    FETCH_PEOPLE_REQUEST,
    FETCH_PEOPLE_FAILURE,
    FETCH_PLANETS_SUCCESS,
    FETCH_PLANETS_REQUEST,
    FETCH_PLANETS_FAILURE,
    FETCH_STARSHIPS_SUCCESS,
    FETCH_STARSHIPS_REQUEST,
    FETCH_STARSHIPS_FAILURE
};
